{"timestamp":"2025-09-08T14:20:05.034842","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-08T14:20:05.035418","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/lignes_azure_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-08T14:20:05.122781Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T14:20:05.122947Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T14:20:05.123033Z","level":"info","event":"Current task name:load_duckdb.to_duckdb_reseau_transport","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T14:20:05.123085Z","level":"info","event":"Dag name:lignes_azure_ETL","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T14:20:05.181637","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"CatalogException","exc_value":"Catalog Error: Table with name \"stops\" already exists!","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1215,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/lignes_azure_dag.py","lineno":34,"name":"duckdb_reseau_transport_call"},{"filename":"/opt/airflow/dags/lignes_azure/gtfs_reseau_transport.py","lineno":40,"name":"export_data_to_duckdb_rt"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-09-08T14:20:05.182886Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T14:20:05.183087Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T14:20:05.183175Z","level":"info","event":"Task:<Task(PythonOperator): load_duckdb.to_duckdb_reseau_transport>","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T14:20:05.183253Z","level":"info","event":"Failure caused by Catalog Error: Table with name \"stops\" already exists!","chan":"stdout","logger":"task"}
