{"timestamp":"2025-09-08T12:08:07.523160","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-08T12:08:07.524289","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/lignes_azure_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-08T12:08:09.427239Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T12:08:09.427413Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T12:08:09.427586Z","level":"info","event":"Current task name:reseau_transport.download_trip_updates","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T12:08:09.427711Z","level":"info","event":"Dag name:lignes_azure_ETL","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T12:08:10.674226","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"HTTPError","exc_value":"404 Client Error: Not Found for url: https://example.com/fichiers.zip","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1215,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/lignes_azure_dag.py","lineno":26,"name":"download_reseau_transport_call"},{"filename":"/opt/airflow/dags/lignes_azure/gtfs_reseau_transport.py","lineno":13,"name":"download_data_rt"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/models.py","lineno":1026,"name":"raise_for_status"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-09-08T12:08:10.677336Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T12:08:10.677685Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T12:08:10.677812Z","level":"info","event":"Task:<Task(PythonOperator): reseau_transport.download_trip_updates>","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T12:08:10.677901Z","level":"info","event":"Failure caused by 404 Client Error: Not Found for url: https://example.com/fichiers.zip","chan":"stdout","logger":"task"}
